FROM node:20-buster-slim

WORKDIR /usr/src/cupejobs_renew_ui

COPY package*.json .
RUN npm install

ARG NEXT_PUBLIC_ARMS_HOST
ARG NEXT_PUBLIC_CUPEJOBS_HOST
ARG NEXT_PUBLIC_MSAL_AUTH_CLIENT_ID
ARG NEXT_PUBLIC_MSAL_AUTH_REDIRECT_URI
ARG NEXT_PUBLIC_MSAL_AUTH_POST_LOGOUT_REDIRECT_URI
ARG NEXT_PUBLIC_MSAL_AUTH_CACHE_LOCATION
ARG NEXT_PUBLIC_MSAL_AUTH_CACHE_STORE_AUTH_STATE_IN_COOKIE

ENV NEXT_PUBLIC_ARMS_HOST=${NEXT_PUBLIC_ARMS_HOST}
ENV NEXT_PUBLIC_CUPEJOBS_HOST=${NEXT_PUBLIC_CUPEJOBS_HOST}

ENV NEXT_PUBLIC_MSAL_AUTH_CLIENT_ID=${NEXT_PUBLIC_MSAL_AUTH_CLIENT_ID}
ENV NEXT_PUBLIC_MSAL_AUTH_REDIRECT_URI=${NEXT_PUBLIC_MSAL_AUTH_REDIRECT_URI}
ENV NEXT_PUBLIC_MSAL_AUTH_POST_LOGOUT_REDIRECT_URI=${NEXT_PUBLIC_MSAL_AUTH_POST_LOGOUT_REDIRECT_URI}
ENV NEXT_PUBLIC_MSAL_AUTH_CACHE_LOCATION=${NEXT_PUBLIC_MSAL_AUTH_CACHE_LOCATION}
ENV NEXT_PUBLIC_MSAL_AUTH_CACHE_STORE_AUTH_STATE_IN_COOKIE=${NEXT_PUBLIC_MSAL_AUTH_CACHE_STORE_AUTH_STATE_IN_COOKIE}

RUN echo "NEXT_PUBLIC_ARMS_HOST=${NEXT_PUBLIC_ARMS_HOST}" >> .env
RUN echo "NEXT_PUBLIC_CUPEJOBS_HOST=${NEXT_PUBLIC_CUPEJOBS_HOST}" >> .env
RUN echo "NEXT_PUBLIC_MSAL_AUTH_CLIENT_ID=${NEXT_PUBLIC_MSAL_AUTH_CLIENT_ID}" >> .env
RUN echo "NEXT_PUBLIC_MSAL_AUTH_REDIRECT_URI=${NEXT_PUBLIC_MSAL_AUTH_REDIRECT_URI}" >> .env
RUN echo "NEXT_PUBLIC_MSAL_AUTH_POST_LOGOUT_REDIRECT_URI=${NEXT_PUBLIC_MSAL_AUTH_POST_LOGOUT_REDIRECT_URI}" >> .env
RUN echo "NEXT_PUBLIC_MSAL_AUTH_CACHE_LOCATION=${NEXT_PUBLIC_MSAL_AUTH_CACHE_LOCATION}" >> .env
RUN echo "NEXT_PUBLIC_MSAL_AUTH_CACHE_STORE_AUTH_STATE_IN_COOKIE=${NEXT_PUBLIC_MSAL_AUTH_CACHE_STORE_AUTH_STATE_IN_COOKIE}" >> .env

COPY . .

RUN npm run build

CMD ["npm", "start"]