FROM node:18.17-buster-slim

WORKDIR /usr/src/cupejobs_renew_ui

COPY package*.json .
RUN npm install

ARG NEXT_PUBLIC_ARMS_HOST
ARG NEXT_PUBLIC_CUPEJOBS_HOST
ENV NEXT_PUBLIC_ARMS_HOST=${NEXT_PUBLIC_ARMS_HOST}
ENV NEXT_PUBLIC_CUPEJOBS_HOST=${NEXT_PUBLIC_CUPEJOBS_HOST}

RUN echo "NEXT_PUBLIC_ARMS_HOST=${NEXT_PUBLIC_ARMS_HOST}" >> .env
RUN echo "NEXT_PUBLIC_CUPEJOBS_HOST=${NEXT_PUBLIC_CUPEJOBS_HOST}" >> .env

COPY . .

RUN npm run build

CMD "npm" "start"