import {LogLevel} from "@/lib/logger";

export const appConfig = {
	name: "CUPE Jobs",
	description: "Contract Academic Employment Opportunities",
	direction: "ltr",
	language: "en",
	theme: "light",
	themeColor: "#090a0b",
	primaryColor: "neonBlue",
	logLevel: process.env.NEXT_PUBLIC_LOG_LEVEL || LogLevel.ALL,
	// authStrategy: process.env.NEXT_PUBLIC_AUTH_STRATEGY || AuthStrategy.NONE,
	fastapi: {
		NEXT_PUBLIC_CUPEJOBS_HOST: process.env.NEXT_PUBLIC_CUPEJOBS_HOST,
		CUPEJOBS_HOST: process.env.CUPEJOBS_HOST,
		CSSP_APPLICATION_PERIOD: '/nra/cssp_application_period',
		CUPE_FACULTY_LIST: '/faculty/cupe_faculties',
		CUPE_FACULTY_UNITS: '/faculty/cupe_faculty_units',
		CUPE1_ASSTS_FEED: '/cupe1assns/cupe1_assns_feed',
		JOBS: '/jobs/',
		JOBS_CSSP: '/jobs/cssp/',
		JOBS_NRA: '/jobs/nra/',
		NEW_POSTINGS_ALERT_URL: '/alerts/new_postings_alert',
		NOTIFICATIONS: '/notifications/read',
		NOTIFICATIONS_ADD: '/notifications/addbatch',
		NOTIFICATIONS_DELETE: '/notifications/deletebatch',
		POSTINGS_FEED_URL: '/postings/faculty_postings_feed',
		USER_LOGOUT_URL: '/users/api/logout',
		USER_ME_URL: '/users/api/user/me',
		USER_REFRESH_URL: '/users/api/refresh',
		USER_TOKEN_URL: '/users/api/token',
		USER_URL: '/users/api/user',

		NEXT_PUBLIC_ARMS_HOST: process.env.NEXT_PUBLIC_ARMS_HOST,
		ARMS_HOST: process.env.ARMS_HOST,
		APPLICANT_DEMOGRAPHIC: '/jobs/applicant_demographic/',
		CURRENT_FISCAL_YEAR: '/faculty/current_fiscal_year',
		INSTRUCTOR_CV: '/jobs/instructor_cv',
		INSTRUCTOR_CV_LAST_UPDATED_DATE: '/jobs/instructor_cv_date',
		INSTRUCTOR_HAS_CV: '/jobs/has_cv',
		INSTRUCTOR_PREV_YEAR_ASSIGNMENTS: '/jobs/last_year_assignments',
		NRA: '/nra/',
		POSTING_URL: '/postings/posting',
		SAVE_ONLINE_APPLICATION_URL: '/jobs/save_online_application',
		UPLOAD_INSTRUCTOR_DOCUMENT: '/jobs/upload_instructor_document',
	},
};
